# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
    paths:
      - '**/src/**'
      - '**/pom.xml'
  pull_request:
    branches: [ master ]
    paths:
      - '**/src/**'
      - '**/pom.xml'

  workflow_dispatch:
    inputs:
      tags:
        description: 'Run reason'
        required: true
        default: 'Simple UI trigger'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 8, 11, 15 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml --no-transfer-progress

  snapshot-check:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Get POM version
        id: get-pom-version
        run: echo "::set-output name=pom-version::$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)"

  cleanup:
    needs: snapshot-check
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ contains(needs.snapshot-check.outputs.pom-version, 'SNAPSHOT') }}

    steps:
      - name: Remove tnt4j package assets
        uses: abrkn/delete-old-github-package-versions@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: Nastel
          packageName: com.jkoolcloud.tnt4j
          minAge: 30s
        continue-on-error: true
      - name: Remove tnt4j-core package assets
        uses: abrkn/delete-old-github-package-versions@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: Nastel
          packageName: com.jkoolcloud.tnt4j-core
          minAge: 30s
        continue-on-error: true
      - name: Remove tnt4j-kafka-sink package assets
        uses: abrkn/delete-old-github-package-versions@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: Nastel
          packageName: com.jkoolcloud.tnt4j-kafka-sink
          minAge: 30s
        continue-on-error: true
      - name: Remove tnt4j-mqtt-sink package assets
        uses: abrkn/delete-old-github-package-versions@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: Nastel
          packageName: com.jkoolcloud.tnt4j-mqtt-sink
          minAge: 30s
        continue-on-error: true

  publish-snapshot:
    needs: snapshot-check
    runs-on: ubuntu-latest
    if: ${{ contains(needs.snapshot-check.outputs.pom-version, 'SNAPSHOT') }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up settings.xml for GitHub Packages
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish SNAPSHOT version to GitHub Packages
        run: mvn -B deploy -DskipTests --file pom.xml --no-transfer-progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
